// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcNY9SsQ_ppyjA5MZkqEJMXnsGTDhOLnw',
    appId: '1:112747563530:web:43fa9b67bd758d760cadf3',
    messagingSenderId: '112747563530',
    projectId: 'warded-6792f',
    authDomain: 'warded-6792f.firebaseapp.com',
    storageBucket: 'warded-6792f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcgKY3vFf5uvbWZ-FdWFjxy8IdAzvl0g4',
    appId: '1:112747563530:android:64e752e064ef6b200cadf3',
    messagingSenderId: '112747563530',
    projectId: 'warded-6792f',
    storageBucket: 'warded-6792f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3kuTItnSkF0qv_N4NReKrm_L5gMNp5Vk',
    appId: '1:112747563530:ios:ac5fc4e46e2f0ec10cadf3',
    messagingSenderId: '112747563530',
    projectId: 'warded-6792f',
    storageBucket: 'warded-6792f.appspot.com',
    iosBundleId: 'com.example.untitle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3kuTItnSkF0qv_N4NReKrm_L5gMNp5Vk',
    appId: '1:112747563530:ios:ac5fc4e46e2f0ec10cadf3',
    messagingSenderId: '112747563530',
    projectId: 'warded-6792f',
    storageBucket: 'warded-6792f.appspot.com',
    iosBundleId: 'com.example.untitle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcNY9SsQ_ppyjA5MZkqEJMXnsGTDhOLnw',
    appId: '1:112747563530:web:1997547f9f49c0c40cadf3',
    messagingSenderId: '112747563530',
    projectId: 'warded-6792f',
    authDomain: 'warded-6792f.firebaseapp.com',
    storageBucket: 'warded-6792f.appspot.com',
  );

}